// Command server runs the fishing rod licence example service.
//
// Every page is generated by Go. Node is not started at run time: GOV.UK Frontend is read from
// node_modules as data (script, assets, fixtures), the stylesheet is compiled ahead of time by
// the Sass pipeline, and component HTML comes from the Go port of Frontend's macros.
//
// Start it with `npm start`, which compiles the stylesheet first. PORT chooses the port
// (default 3000). HOST selects the bind address (empty = 0.0.0.0 on tcp4, which Render's
// port scan can see; use HOST=127.0.0.1 for local-only). NODE_ENV=production turns off the
// component catalogue and example pages unless DEMOS_ENABLED=true (used on the public Render demo).
package main

import (
	"context"
	"errors"
	"fmt"
	"log/slog"
	"net"
	"net/http"
	"os"
	"os/signal"
	"syscall"
	"time"

	"github.com/Nooshu/govuk-frontend-example-go/internal/app"
	"github.com/Nooshu/govuk-frontend-example-go/internal/config"
	"github.com/Nooshu/govuk-frontend-example-go/internal/govukrender"
)

func main() {
	logger := slog.New(slog.NewTextHandler(os.Stderr, nil))
	if err := run(logger); err != nil {
		logger.Error("the service could not start", "error", err)
		os.Exit(1)
	}
}

// run starts the HTTP server and blocks until SIGINT/SIGTERM or a serve error.
//
// Timeouts bound slow clients; Shutdown drains in-flight requests for up to 10s.
func run(logger *slog.Logger) error {
	cfg, err := config.Load()
	if err != nil {
		return err
	}
	network, addr, err := config.ResolveListen(os.Getenv)
	if err != nil {
		return err
	}
	handler, err := app.New(app.Options{
		Config:       cfg,
		Components:   govukrender.New(),
		DemosEnabled: config.DemosEnabled(os.Getenv),
		Logger:       logger,
	})
	if err != nil {
		return err
	}

	server := &http.Server{
		Handler: handler,
		// Timeouts bound how long one slow or stalled client can hold a connection open.
		ReadHeaderTimeout: 5 * time.Second,
		ReadTimeout:       15 * time.Second,
		WriteTimeout:      30 * time.Second,
		IdleTimeout:       60 * time.Second,
		ErrorLog:          slog.NewLogLogger(logger.Handler(), slog.LevelWarn),
	}

	listener, err := net.Listen(network, addr)
	if err != nil {
		return fmt.Errorf("listening on %s: %w", addr, err)
	}
	logger.Info("example service started",
		"addr", listener.Addr().String(),
		"govukFrontend", cfg.FrontendVersion,
		"demos", config.DemosEnabled(os.Getenv),
	)

	ctx, stop := signal.NotifyContext(context.Background(), os.Interrupt, syscall.SIGTERM)
	defer stop()

	serving := make(chan error, 1)
	go func() { serving <- server.Serve(listener) }()

	select {
	case err := <-serving:
		if errors.Is(err, http.ErrServerClosed) {
			return nil
		}
		return err
	case <-ctx.Done():
		shutdown, cancel := context.WithTimeout(context.Background(), 10*time.Second)
		defer cancel()
		return server.Shutdown(shutdown)
	}
}
