// Command server runs the rod fishing licence example service.
//
// Every page is generated by Go. Node is not started at run time: GOV.UK Frontend is read from
// node_modules as data (script, assets, fixtures), the stylesheet is compiled ahead of time by
// the Sass pipeline, and component HTML comes from the Go port of Frontend's macros.
//
// Start it with `npm start`, which compiles the stylesheet first. PORT chooses the port and
// defaults to 3000; setting NODE_ENV=production turns off the component catalogue and the
// example pages.
package main

import (
	"context"
	"errors"
	"fmt"
	"log/slog"
	"net"
	"net/http"
	"os"
	"os/signal"
	"syscall"
	"time"

	"github.com/Nooshu/govuk-frontend-example-go/internal/app"
	"github.com/Nooshu/govuk-frontend-example-go/internal/config"
	"github.com/Nooshu/govuk-frontend-example-go/internal/govukrender"
)

func main() {
	logger := slog.New(slog.NewTextHandler(os.Stderr, nil))
	if err := run(logger); err != nil {
		logger.Error("the service could not start", "error", err)
		os.Exit(1)
	}
}

func run(logger *slog.Logger) error {
	cfg, err := config.Load()
	if err != nil {
		return err
	}
	port, err := config.ResolvePort(os.Getenv)
	if err != nil {
		return err
	}
	handler, err := app.New(app.Options{
		Config:       cfg,
		Components:   govukrender.New(),
		DemosEnabled: config.DemosEnabled(os.Getenv),
		Logger:       logger,
	})
	if err != nil {
		return err
	}

	server := &http.Server{
		Handler: handler,
		// Timeouts bound how long one slow or stalled client can hold a connection open.
		ReadHeaderTimeout: 5 * time.Second,
		ReadTimeout:       15 * time.Second,
		WriteTimeout:      30 * time.Second,
		IdleTimeout:       60 * time.Second,
		ErrorLog:          slog.NewLogLogger(logger.Handler(), slog.LevelWarn),
	}

	listener, err := net.Listen("tcp", fmt.Sprintf("127.0.0.1:%d", port))
	if err != nil {
		return fmt.Errorf("listening on port %d: %w", port, err)
	}
	logger.Info("example service started",
		"url", fmt.Sprintf("http://%s", listener.Addr()),
		"govukFrontend", cfg.FrontendVersion,
		"demos", config.DemosEnabled(os.Getenv),
	)

	ctx, stop := signal.NotifyContext(context.Background(), os.Interrupt, syscall.SIGTERM)
	defer stop()

	serving := make(chan error, 1)
	go func() { serving <- server.Serve(listener) }()

	select {
	case err := <-serving:
		if errors.Is(err, http.ErrServerClosed) {
			return nil
		}
		return err
	case <-ctx.Done():
		shutdown, cancel := context.WithTimeout(context.Background(), 10*time.Second)
		defer cancel()
		return server.Shutdown(shutdown)
	}
}
